pipeline:
  build:
    image: jguyomard/hugo-builder
    commands:
      - hugo

  publish:
    image: plugins/docker
    username: ${DRONE_USERNAME}
    password: ${DRONE_PASSWORD}
    registry: hub.docker.com
    repo: youkoulayley/wiki-serieall
    tags:
      - latest
      - ${DRONE_BRANCH/\//-}