pipeline:
  build:
    image: jguyomard/hugo-builder
    commands:
      - hugo

  publish:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: youkoulayley/wiki-serieall
    tags:
      - latest
      - ${DRONE_BRANCH/\//-}