pipeline:
  build:
    image: giantswarm/hugo
    commands:
      - hugo

  publish:
    image: plugins/docker
    username: ${DRONE_USERNAME}
    password: ${DRONE_PASSWORD}
    repo: youkoulayley/wiki-serieall
    tags:
      - latest
      - ${DRONE_BRANCH/\//-}