pipeline:
  build:
    image: samueldebruyn/hugo-build
    commands:
      - hugo

  publish:
    image: plugins/docker
    username: ${DRONE_USERNAME}
    password: ${DRONE_PASSWORD}
    repo: youkoulayley/wiki-serieall
    tags:
      - latest
      - ${DRONE_BRANCH/\//-}